#!/usr/bin/env python3
"""
Generate a stub LWJGL OpenAL native surface for the wasm JVM.

We don't port real audio; we make paulscode's LibraryLWJGLOpenAL.init() SUCCEED so
it doesn't leave a half-initialised library that later NPEs in
SoundSystem.playing() and crashes Minecraft. So devices/contexts "open", sources
and buffers get fake ids, errors report none, and sources report AL_STOPPED.
Everything else is a no-op. Result: silent audio, no crash.

Usage: gen-al.py <lwjgl.jar> <out.c> <Class> [<Class> ...]   (classes under org.lwjgl.openal)
"""
import re, subprocess, sys

# java type -> (JNI C type, is it a pointer-ish long)
JNI = {'void':'void','int':'jint','float':'jfloat','long':'jlong','boolean':'jboolean',
       'java.lang.String':'jstring','java.nio.ByteBuffer':'jobject','java.nio.IntBuffer':'jobject'}
NAT = re.compile(r'(?:private\s+|public\s+)?static\s+native\s+(\S+)\s+(\w+)\s*\((.*?)\)[^;]*;')

def jni_mangle(s): return s.replace('_', '_1')

def gen_body(ret, name, argtypes):
    """Return C body producing values that keep paulscode happy."""
    a = [f'a{i}' for i in range(len(argtypes))]
    if name.endswith('GetError'):                     return 'return 0;'                 # AL/ALC_NO_ERROR
    if name in ('nalcOpenDevice','nalcCreateContext',
                'nalcGetCurrentContext','nalcGetContextsDevice'): return 'return (jlong)0x1;'  # fake handle
    if name in ('nalcMakeContextCurrent','nalcCloseDevice','nalcIsExtensionPresent'): return 'return 1;'  # ALC_TRUE
    if name in ('nalGenSources','nalGenBuffers'):     # (int n, long ptr) -> fill ids
        return f'int* p=(int*)(intptr_t){a[1]}; for(int i=0;i<{a[0]};i++) p[i]=++g_al_id;'
    if name in ('nalGenSources2','nalGenBuffers2'):   return 'return ++g_al_id;'
    if name == 'nalGetSourcei':                       return f'return {a[1]}==0x1010 ? 0x1015 : 0;'  # SOURCE_STATE->STOPPED
    if name.startswith('nalIs'):                      return 'return 1;'
    if ret == 'java.nio.ByteBuffer':                  return '(void)env; return (*env)->NewDirectByteBuffer(env, g_al_str, sizeof g_al_str);'
    if ret == 'java.lang.String':                     return 'return (*env)->NewStringUTF(env, "");'
    if ret in ('int','float','long','boolean'):       return 'return 0;'
    return ''                                          # void

def gen_class(jar, simple):
    fqcn = 'org.lwjgl.openal.' + simple
    out = subprocess.run(['javap','-p','-classpath',jar,fqcn], capture_output=True, text=True).stdout
    lines = []
    prefix = 'Java_org_lwjgl_openal_' + jni_mangle(simple) + '_'
    from collections import Counter
    methods = [(m.group(1), m.group(2), [t.strip() for t in m.group(3).split(',') if t.strip()])
               for m in NAT.finditer(out)]
    counts = Counter(n for _, n, _ in methods)
    for ret, name, args in methods:
        if ret not in JNI or any(t not in JNI for t in args):
            # unknown type in signature -> emit a void no-op if it returns void, else skip
            if ret != 'void': continue
        cret = JNI.get(ret, 'void')
        decl = ['JNIEnv* env', 'jclass cls']
        for i, t in enumerate(args):
            decl.append(f'{JNI.get(t,"jlong")} a{i}')
        sym = prefix + jni_mangle(name)
        if counts[name] > 1:
            frag = ''.join({'int':'I','float':'F','long':'J','boolean':'Z',
                            'java.lang.String':'Ljava_lang_String_2',
                            'java.nio.ByteBuffer':'Ljava_nio_ByteBuffer_2',
                            'java.nio.IntBuffer':'Ljava_nio_IntBuffer_2'}.get(t,'J') for t in args)
            sym += '__' + frag
        body = gen_body(ret, name, args)
        lines.append(f'JNIEXPORT {cret} JNICALL {sym}(' + ', '.join(decl) + ') { ' + body + ' }')
    return lines

def main():
    jar, outc = sys.argv[1], sys.argv[2]
    classes = sys.argv[3:]
    alllines = []
    for c in classes:
        ls = gen_class(jar, c)
        alllines.append(f'/* ---- {c}: {len(ls)} stubs ---- */')
        alllines += ls
    with open(outc, 'w') as f:
        f.write('/* GENERATED by gen-al.py — stub LWJGL OpenAL (silent, non-crashing). */\n')
        f.write('#include <jni.h>\n#include <stdint.h>\n\n')
        f.write('int g_al_id = 0;\n')
        f.write('unsigned char g_al_str[64] = {0};\n\n')
        f.write('\n'.join(alllines))
        f.write('\n')
    sys.stderr.write(f'gen-al.py: {sum(1 for l in alllines if l.startswith("JNIEXPORT"))} OpenAL stubs -> {outc}\n')

if __name__ == '__main__':
    main()
