version=1
serif.plain.alphabetic=Roboto
serif.bold.alphabetic=Roboto
serif.italic.alphabetic=Roboto
serif.bolditalic.alphabetic=Roboto
sansserif.plain.alphabetic=Roboto
sansserif.bold.alphabetic=Roboto
sansserif.italic.alphabetic=Roboto
sansserif.bolditalic.alphabetic=Roboto
monospaced.plain.alphabetic=Roboto
monospaced.bold.alphabetic=Roboto
monospaced.italic.alphabetic=Roboto
monospaced.bolditalic.alphabetic=Roboto
dialog.plain.alphabetic=Roboto
dialog.bold.alphabetic=Roboto
dialog.italic.alphabetic=Roboto
dialog.bolditalic.alphabetic=Roboto
dialoginput.plain.alphabetic=Roboto
dialoginput.bold.alphabetic=Roboto
dialoginput.italic.alphabetic=Roboto
dialoginput.bolditalic.alphabetic=Roboto
sequence.allfonts=alphabetic
filename.Roboto=/jdk/lib/fonts/Roboto.ttf
